name: slim_conservation_scoring
channels:
  - pytorch
  - bioconda
  - conda-forge
dependencies:
  - python-dotenv
  - openpyxl
  - attrs
  - babel
  - beautifulsoup4
  - biopython>=1.8
  - importlib_resources
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - pandas
  - pip
  - python
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - tabulate
  - torchvision
  - tornado
  - yaml
  - pip:
      - alfpy
      - fair-esm
      - logomaker
      - regex
      - tqdm
      - transformers
